name: Selenium IDE CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
       chrome-version: 120
    - name: Install dependencies
      run: dontnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run tests
      env:
       CHROMEWEBDRIVER: /usr/bin/google-chrome-stable
      run: dotnet test --verbosity normal
